# =================================================================
#        Render Blueprint for Blox Battles (Final Version)
# =================================================================
#
# This version is corrected according to the official Render Blueprint
# documentation provided in the screenshots. It uses the correct syntax
# for both the database and the static site frontend.
#

# --- Database Definition ---
# Databases are defined in their own top-level block.
databases:
  - name: blox_battles_db
    postgresMajorVersion: "15"
    region: oregon
    plan: basic-256mb

services:
  # --- Backend API Service ---
  - type: web
    name: blox_battles_api
    env: node
    plan: starter
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/status
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox_battles_db
          property: connectionString
      - key: NODE_VERSION
        value: "18.17.1"
      # These URLs are based on the service names defined in this file.
      - key: SERVER_URL # Frontend URL
        value: https://blox_battles_web.onrender.com
      - key: BACKEND_URL # This service's own URL
        value: https://blox_battles_api.onrender.com
      # ---
      # --- SECRET & SENSITIVE VARIABLES (Set these in Render Dashboard) ---
      # ---
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

  # --- Frontend Web Service (Corrected Syntax) ---
  - type: web
    name: blox_battles_web
    runtime: static
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # CORRECTED: The backend URL is explicitly defined.
      # The 'fromService' directive does not support the 'url' property for web services.
      - key: VITE_API_URL
        value: https://blox_battles_api.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
