# render.yaml
# Blueprint for deploying the Blox Battles application on Render.
# This file specifies the services, databases, and environment configurations
# required to run the full-stack application.
# Last Updated: 2025-07-23

databases:
  - name: blox-battles-db
    postgresMajorVersion: "15" 
    plan: basic-256mb

services:
  # 1. Backend API Service (Node.js / Express)
  - type: web
    name: blox-battles-api 
    env: node
    rootDir: ./backend
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      # --- Render-Managed Variables ---
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      
      - key: BASE_URL
        value: "https://blox-battles-api.onrender.com"

      # CORRECTED: The public URL of the frontend must be set statically.
      - key: FRONTEND_URL
        value: "https://blox-battles-frontend.onrender.com"
      
      # --- Application Secrets (MUST be set in Render Dashboard) ---
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: ADMIN_API_KEY 
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
        
  # 2. Frontend Static Site (React / Vite)
  - type: web 
    name: blox-battles-frontend
    runtime: static 
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist 
    envVars:
      # Pass the Stripe publishable key to the frontend build
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: pk_test_51RlQKOQY4V3Boe3I209Q0Z6cxmV1erjwaNRjbtoMdSsMMUoyvUXLZFNttt3g9fat01ZeqhxyokgghMJFwxtng2HB00u53r7ngQ
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://blox-battles-api.onrender.com/api/:path*
      - type: rewrite
        source: /*
        destination: /index.html
