databases:
  - name: blox-battles-db
    postgresMajorVersion: "15"
    region: oregon
    plan: starter
    ipAllowList: []

services:
  - type: web
    runtime: node
    name: blox-battles-api
    plan: starter
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      - key: SERVER_URL
        value: https://blox-battles-app.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false

  - type: web
    runtime: static
    name: blox-battles-app
    plan: starter
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://blox-battles-api.onrender.com/api
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
