# render.yaml
# Defines the services for your Blox-Battles application on Render.
# This Blueprint will create a PostgreSQL database, a Node.js backend,
# and a static React frontend.

services:
  # 1. PostgreSQL Database Service
  - type: psql
    name: blox-battles-db
    plan: starter # Render's starter plan is suitable for production launch.
    region: oregon # Choose the region closest to your users.
    ipAllowList: [] # Allows access from any Render service, required for the backend.
    postgresMajorVersion: 15

  # 2. Backend Web Service (Node.js/Express)
  - type: web
    name: blox-battles-api
    plan: starter
    region: oregon
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          type: psql
          name: blox-battles-db
          property: connectionString
      - key: SERVER_URL
        value: https://blox-battles-app.onrender.com # Your frontend's public URL
      # --- [SECURE] Path to the secret file containing the private key ---
      - key: PAYOUT_WALLET_PRIVATE_KEY_PATH
        value: /etc/secrets/payout_wallet_private_key
      # --- All other secrets will be added via the Render Dashboard ---
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false

  # 3. Frontend Static Site (React/Vite)
  - type: web
    name: blox-battles-app
    plan: starter
    region: oregon
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://blox-battles-api.onrender.com/api # The public URL of your new backend
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
