# v2
# This version removes optional VAPID keys for push notifications
# and the ADMIN_TEST_API_KEY to simplify production configuration.
# =================================================================

# --- Database Definition ---
databases:
  - name: blox_battles_db
    postgresMajorVersion: "15"
    region: oregon
    plan: basic-256mb

services:
  # --- Backend API Service ---
  - type: web
    name: blox_battles_api
    env: node
    plan: starter
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/status
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox_battles_db
          property: connectionString
      - key: NODE_VERSION
        value: "18.17.1"
      - key: SERVER_URL # Frontend URL
        value: https://blox_battles_web.onrender.com
      - key: BACKEND_URL # This service's own URL
        value: https://blox_battles_api.onrender.com
      # --- SECRET & SENSITIVE VARIABLES (Set these in Render Dashboard) ---
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

  # --- Frontend Web Service ---
  - type: web
    name: blox_battles_web
    runtime: static
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://blox_battles_api.onrender.com/api/:path*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
