# render.yaml
# This file defines the services for your application for Render.
# You can deploy all services at once by creating a "Blueprint"
# in Render and pointing it to your Git repository.

databases:
  - name: blox-battles-db
    plan: starter # 'starter' is sufficient for most applications.
    region: oregon
    ipAllowList: [] # Allows access from any IP, suitable for Render services.
    postgresMajorVersion: 15

services:
  # 1. Backend Web Service (Node.js/Express)
  - type: web
    name: blox-battles-api
    plan: starter
    region: oregon
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      - key: SERVER_URL
        value: https://blox-battles-app.onrender.com
      # Secrets (set in Render Dashboard only)
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false

  # 2. Frontend Static Site (React/Vite)
  - type: web
    name: blox-battles-app
    plan: starter
    region: oregon
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://blox-battles-api.onrender.com/api
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
