# =================================================================
#        Render Blueprint for Blox Battles (Corrected)
# =================================================================
#
# This file defines the infrastructure for the Blox Battles application.
# It consists of three services:
#   1. blox_battles_db: A PostgreSQL database.
#   2. blox_battles_api: The Node.js/Express backend web service.
#   3. blox_battles_web: The React/Vite frontend static site.
#
# All service names have been updated to use 'blox_battles' as requested.
#

# ------------------
#  Database Service
# ------------------
databases:
  - name: blox-battles-db
    plan: Basic-250mb # 'starter' is sufficient for most applications.
    region: oregon
    ipAllowList: [] # Allows access from any IP, suitable for Render services.
    postgresMajorVersion: 15
    pgaUpgrade:
      enabled: false

services:

  # ------------------
  #  Backend API Service
  # ------------------
  - type: web
    name: blox_battles_api
    env: node
    plan: starter # Specifies the lowest paid instance type.
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/status
    envVars:
      # This pulls the connection string directly from the database service created above.
      - key: DATABASE_URL
        fromService:
          type: psql
          name: blox_battles_db
          property: connectionString
      # The Node.js version to use. It's good practice to specify it.
      - key: NODE_VERSION
        value: 18.17.1
      # This will be the public URL of your frontend service.
      # It's constructed from the name of the frontend service defined below.
      - key: SERVER_URL
        value: https://blox_battles_web.onrender.com
      # This will be the public URL of this backend service itself.
      - key: BACKEND_URL
        value: https://blox_battles_api.onrender.com
      # ---
      # --- CRITICAL: SECRET & SENSITIVE VARIABLES ---
      # ---
      # The following keys are sensitive. You MUST set their values as
      # 'Secret Files' or 'Environment Variables' in the Render dashboard
      # under the 'Environment' tab for the 'blox_battles_api' service.
      # The 'sync: false' property prevents Render from overwriting a value
      # set in the dashboard with an empty one from this file.
      #
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      # The Stripe publishable key is also needed by the backend for some operations.
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

  # --------------------
  #  Frontend Web Service
  # --------------------
  - type: static_site
    name: blox_battles_web
    env: static
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishPath: "./dist" # The output directory for the Vite build.
    # Rewrite rule to support client-side routing (e.g., React Router).
    # All paths that are not files are redirected to the root index.html.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # This injects the backend URL into the frontend build process,
      # making it available as `import.meta.env.VITE_API_URL`.
      - key: VITE_API_URL
        value: https://blox_battles_api.onrender.com
      # The Stripe publishable key for the frontend.
      # You MUST set this as a secret in the Render dashboard for the 'blox_battles_web' service.
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
