# /render.yaml
# This file defines the infrastructure for the Blox Battles platform on Render.
# It specifies the database, three services (backend, frontend, cron), and one worker (Discord bot).

databases:
  - name: blox-battles-db
    plan: basic-256mb
    region: oregon

services:
  # ---------------------
  # 1. The Backend API Service (Node.js/Express)
  # ---------------------
  - type: web
    name: blox-battles-backend
    runtime: node
    plan: starter
    region: oregon
    rootDir: ./backend
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      - key: SERVER_URL # The public URL of the frontend
        value: https://blox-battles-frontend.onrender.com
      - key: BACKEND_URL # This service's own public URL
        value: https://blox-battles-backend.onrender.com
